/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Barbig
 */
public class HomeAdmin extends javax.swing.JFrame {

    /**
     * Creates new form HomeAdmin
     */
    public static String ID_Order = "";
    public static String ID_acc = "";
    public static String ID_Room = "";
    int itotalaccount = 0;
    int itotalrooms = 0;
    int itotalorder = 0;

    DefaultTableModel acctable;
    DefaultTableModel tableorder;
    DefaultTableModel roomtable;

    public HomeAdmin() {

        initComponents();

        this.setTitle("ADMIN");

        jLabel2.setText("  " + new Login().Name.toUpperCase());
        dashboard1.setVisible(true);
        account1.setVisible(false);
        room1.setVisible(false);
        oder1.setVisible(false);

        dashboard.setBackground(new Color(51, 255, 255));
        account.setBackground(new Color(153, 255, 255));
        room.setBackground(new Color(153, 255, 255));
        order.setBackground(new Color(153, 255, 255));

        showroom();
        showacc();
        showorder();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        logout = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        account = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        dashboard = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        room = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        order = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        dashboard1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        totalacc = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        totalrooms = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        totalorder = new javax.swing.JLabel();
        oder1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        orderroom = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        bteditaccount2 = new javax.swing.JButton();
        room1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableroom = new javax.swing.JTable();
        bteditroom = new javax.swing.JButton();
        btdeleteroom = new javax.swing.JButton();
        btaddroom = new javax.swing.JButton();
        bteditaccount3 = new javax.swing.JButton();
        account1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableacc = new javax.swing.JTable();
        bteditaccount = new javax.swing.JButton();
        btdeleteaccount = new javax.swing.JButton();
        btaddaccount = new javax.swing.JButton();
        bteditaccount1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Management");

        logout.setBackground(new java.awt.Color(153, 255, 255));
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconlogout30px.png"))); // NOI18N
        jLabel7.setText("  Logout");

        javax.swing.GroupLayout logoutLayout = new javax.swing.GroupLayout(logout);
        logout.setLayout(logoutLayout);
        logoutLayout.setHorizontalGroup(
            logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoutLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        logoutLayout.setVerticalGroup(
            logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(153, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 0, 2, 0, new java.awt.Color(255, 255, 255)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconauser50px.png"))); // NOI18N
        jLabel2.setText("    Name");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        account.setBackground(new java.awt.Color(153, 255, 255));
        account.setPreferredSize(new java.awt.Dimension(337, 74));
        account.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accountMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconaccount30px.png"))); // NOI18N
        jLabel4.setText("  Account");

        javax.swing.GroupLayout accountLayout = new javax.swing.GroupLayout(account);
        account.setLayout(accountLayout);
        accountLayout.setHorizontalGroup(
            accountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        accountLayout.setVerticalGroup(
            accountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, accountLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        dashboard.setBackground(new java.awt.Color(153, 255, 255));
        dashboard.setPreferredSize(new java.awt.Dimension(337, 74));
        dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icondashboard.png"))); // NOI18N
        jLabel3.setText("  Dashboard");

        javax.swing.GroupLayout dashboardLayout = new javax.swing.GroupLayout(dashboard);
        dashboard.setLayout(dashboardLayout);
        dashboardLayout.setHorizontalGroup(
            dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dashboardLayout.setVerticalGroup(
            dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        room.setBackground(new java.awt.Color(153, 255, 255));
        room.setPreferredSize(new java.awt.Dimension(337, 74));
        room.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roomMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconroom30px.png"))); // NOI18N
        jLabel5.setText("  Room");

        javax.swing.GroupLayout roomLayout = new javax.swing.GroupLayout(room);
        room.setLayout(roomLayout);
        roomLayout.setHorizontalGroup(
            roomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roomLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        roomLayout.setVerticalGroup(
            roomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roomLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        order.setBackground(new java.awt.Color(153, 255, 255));
        order.setPreferredSize(new java.awt.Dimension(337, 74));
        order.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                orderMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconorder30px.png"))); // NOI18N
        jLabel6.setText("  Order");

        javax.swing.GroupLayout orderLayout = new javax.swing.GroupLayout(order);
        order.setLayout(orderLayout);
        orderLayout.setHorizontalGroup(
            orderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orderLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        orderLayout.setVerticalGroup(
            orderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, orderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel12.setBackground(new java.awt.Color(153, 255, 255));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 337, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 74, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(64, 64, 64))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(account, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(logout, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(room, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(order, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(account, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(room, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(order, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(114, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        dashboard1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel11.setText("Dashboard");

        jPanel4.setBackground(new java.awt.Color(204, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jPanel4.setPreferredSize(new java.awt.Dimension(300, 170));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Total Account");

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconadmin100px.png"))); // NOI18N

        totalacc.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        totalacc.setText("0");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(totalacc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(22, 22, 22))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(totalacc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel13))
                .addGap(26, 26, 26))
        );

        jPanel5.setBackground(new java.awt.Color(204, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jPanel5.setPreferredSize(new java.awt.Dimension(300, 170));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Total Rooms");

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconrooms100px.png"))); // NOI18N

        totalrooms.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        totalrooms.setText("0");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(totalrooms))
                .addGap(60, 60, 60)
                .addComponent(jLabel15)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(totalrooms)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)))
                .addGap(19, 19, 19))
        );

        jPanel6.setBackground(new java.awt.Color(204, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jPanel6.setPreferredSize(new java.awt.Dimension(300, 170));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("Total Order");

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconorder100px.png"))); // NOI18N

        totalorder.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        totalorder.setText("0");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(totalorder))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel17)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(totalorder)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout dashboard1Layout = new javax.swing.GroupLayout(dashboard1);
        dashboard1.setLayout(dashboard1Layout);
        dashboard1Layout.setHorizontalGroup(
            dashboard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboard1Layout.createSequentialGroup()
                .addGroup(dashboard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dashboard1Layout.createSequentialGroup()
                        .addGap(460, 460, 460)
                        .addComponent(jLabel11))
                    .addGroup(dashboard1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        dashboard1Layout.setVerticalGroup(
            dashboard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboard1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(63, 63, 63)
                .addGroup(dashboard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(458, Short.MAX_VALUE))
        );

        oder1.setBackground(new java.awt.Color(255, 255, 255));
        oder1.setPreferredSize(new java.awt.Dimension(1091, 705));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel8.setText("Order");

        orderroom.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Fullname", "Phone number", "Check-in date", "Check-out date", "Rooms order", "Note", "ID User Order", "Status", "Time"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(orderroom);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconV.png"))); // NOI18N
        jButton1.setText("  Accept");
        jButton1.setPreferredSize(new java.awt.Dimension(140, 50));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconx.png"))); // NOI18N
        jButton2.setText("  Refuse");
        jButton2.setPreferredSize(new java.awt.Dimension(140, 50));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        bteditaccount2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconlammoi.png"))); // NOI18N
        bteditaccount2.setText("  Refresh");
        bteditaccount2.setActionCommand("  Edit room");
        bteditaccount2.setPreferredSize(new java.awt.Dimension(150, 50));
        bteditaccount2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bteditaccount2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout oder1Layout = new javax.swing.GroupLayout(oder1);
        oder1.setLayout(oder1Layout);
        oder1Layout.setHorizontalGroup(
            oder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(oder1Layout.createSequentialGroup()
                .addGroup(oder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(oder1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3))
                    .addGroup(oder1Layout.createSequentialGroup()
                        .addGap(513, 513, 513)
                        .addComponent(jLabel8)
                        .addGap(0, 476, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(oder1Layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(201, 201, 201)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bteditaccount2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116))
        );
        oder1Layout.setVerticalGroup(
            oder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(oder1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(26, 26, 26)
                .addGroup(oder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bteditaccount2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE)
                .addContainerGap())
        );

        room1.setBackground(new java.awt.Color(255, 255, 255));
        room1.setPreferredSize(new java.awt.Dimension(1091, 705));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel9.setText("Room");

        tableroom.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Number room", "Status", "Booking person ID", "TIme"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableroom);

        bteditroom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconedit.png"))); // NOI18N
        bteditroom.setText("  Edit");
        bteditroom.setActionCommand("  Edit room");
        bteditroom.setPreferredSize(new java.awt.Dimension(150, 50));
        bteditroom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bteditroomActionPerformed(evt);
            }
        });

        btdeleteroom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconx.png"))); // NOI18N
        btdeleteroom.setText("  Delete");
        btdeleteroom.setPreferredSize(new java.awt.Dimension(150, 50));
        btdeleteroom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btdeleteroomActionPerformed(evt);
            }
        });

        btaddroom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconaddd.png"))); // NOI18N
        btaddroom.setText("  Add");
        btaddroom.setPreferredSize(new java.awt.Dimension(150, 50));
        btaddroom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btaddroomActionPerformed(evt);
            }
        });

        bteditaccount3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconlammoi.png"))); // NOI18N
        bteditaccount3.setText("  Refresh");
        bteditaccount3.setActionCommand("  Edit room");
        bteditaccount3.setPreferredSize(new java.awt.Dimension(150, 50));
        bteditaccount3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bteditaccount3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout room1Layout = new javax.swing.GroupLayout(room1);
        room1.setLayout(room1Layout);
        room1Layout.setHorizontalGroup(
            room1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(room1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(room1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(room1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, room1Layout.createSequentialGroup()
                        .addGap(0, 446, Short.MAX_VALUE)
                        .addGroup(room1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, room1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(484, 484, 484))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, room1Layout.createSequentialGroup()
                                .addComponent(btaddroom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bteditroom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btdeleteroom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bteditaccount3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );
        room1Layout.setVerticalGroup(
            room1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(room1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(24, 24, 24)
                .addGroup(room1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bteditroom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btaddroom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btdeleteroom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bteditaccount3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE)
                .addContainerGap())
        );

        account1.setBackground(new java.awt.Color(255, 255, 255));
        account1.setPreferredSize(new java.awt.Dimension(1091, 705));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel10.setText("Account");

        tableacc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Username", "Phone number", "Password", "Role", "Time"
            }
        ));
        jScrollPane1.setViewportView(tableacc);

        bteditaccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconlammoi.png"))); // NOI18N
        bteditaccount.setText("  Refresh");
        bteditaccount.setActionCommand("  Edit room");
        bteditaccount.setPreferredSize(new java.awt.Dimension(150, 50));
        bteditaccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bteditaccountActionPerformed(evt);
            }
        });

        btdeleteaccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconx.png"))); // NOI18N
        btdeleteaccount.setText(" Delete");
        btdeleteaccount.setPreferredSize(new java.awt.Dimension(150, 50));
        btdeleteaccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btdeleteaccountActionPerformed(evt);
            }
        });

        btaddaccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconaddd.png"))); // NOI18N
        btaddaccount.setText("  Add");
        btaddaccount.setPreferredSize(new java.awt.Dimension(150, 50));
        btaddaccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btaddaccountActionPerformed(evt);
            }
        });

        bteditaccount1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconedit.png"))); // NOI18N
        bteditaccount1.setText("  Edit");
        bteditaccount1.setActionCommand("  Edit room");
        bteditaccount1.setPreferredSize(new java.awt.Dimension(150, 50));
        bteditaccount1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bteditaccount1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout account1Layout = new javax.swing.GroupLayout(account1);
        account1.setLayout(account1Layout);
        account1Layout.setHorizontalGroup(
            account1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(account1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(account1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(account1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, account1Layout.createSequentialGroup()
                        .addGap(0, 418, Short.MAX_VALUE)
                        .addGroup(account1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, account1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(479, 479, 479))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, account1Layout.createSequentialGroup()
                                .addComponent(btaddaccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bteditaccount1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btdeleteaccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bteditaccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40))))))
        );
        account1Layout.setVerticalGroup(
            account1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(account1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(account1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bteditaccount1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btaddaccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bteditaccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btdeleteaccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dashboard1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(account1, javax.swing.GroupLayout.DEFAULT_SIZE, 1131, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(room1, javax.swing.GroupLayout.DEFAULT_SIZE, 1131, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(oder1, javax.swing.GroupLayout.DEFAULT_SIZE, 1131, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dashboard1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(account1, javax.swing.GroupLayout.DEFAULT_SIZE, 722, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(room1, javax.swing.GroupLayout.DEFAULT_SIZE, 722, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(oder1, javax.swing.GroupLayout.DEFAULT_SIZE, 722, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1058, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void showorder() {
        itotalorder = 0;
        String sqlorder = "SELECT * FROM `oder` ORDER BY `oder`.`ID_oder` DESC";

        tableorder = (DefaultTableModel) orderroom.getModel();
        tableorder.setNumRows(0);
        try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/" + Config.DATABASENAME, Config.USER, Config.PASS);
            Statement sttorder = conn.createStatement();
            ResultSet rsorder = sttorder.executeQuery(sqlorder);
            while (rsorder.next()) {
                tableorder.addRow(new Object[]{rsorder.getString("ID_oder"), rsorder.getString("fullname"), rsorder.getString("phone"), rsorder.getString("check_in_date"), rsorder.getString("check_in_date"), rsorder.getString("rooms"), rsorder.getString("note"), rsorder.getString("ID_User_Oder"), rsorder.getString("stt_oder"), rsorder.getString("log_oder")});
                itotalorder++;
            }
            conn.close();
        } catch (SQLException ex) {
            Logger.getLogger(HomeAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        ListSelectionModel lmorder = orderroom.getSelectionModel();
        lmorder.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        totalorder.setText(Integer.toString(itotalorder));
    }

    public void showroom() {
        itotalrooms = 0;
        roomtable = (DefaultTableModel) tableroom.getModel();
        roomtable.setNumRows(0);
        String sqlroom = "SELECT * FROM `rooms`;";
        try {

            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/" + Config.DATABASENAME, Config.USER, Config.PASS);

            Statement sttroom = conn.createStatement();
            ResultSet rsroom = sttroom.executeQuery(sqlroom);

            while (rsroom.next()) {
                roomtable.addRow(new Object[]{rsroom.getString("ID_Room"), rsroom.getString("Number_room"), rsroom.getString("Stt_room"), rsroom.getString("Booking_person_ID"), rsroom.getString("Log_room")});
                itotalrooms++;
            }

            conn.close();
        } catch (SQLException ex) {
            Logger.getLogger(Rooms.class.getName()).log(Level.SEVERE, null, ex);
        }
        ListSelectionModel lroom = tableroom.getSelectionModel();
        lroom.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        totalrooms.setText(Integer.toString(itotalrooms));

    }

    public void showacc() {
        itotalaccount = 0;
//        acctable.setNumRows(0);
        acctable = (DefaultTableModel) tableacc.getModel();
        acctable.setNumRows(0);
        String sqlacc = "SELECT * FROM `account`;";

        try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/" + Config.DATABASENAME, Config.USER, Config.PASS);

            Statement sttmacc = conn.createStatement();
            ResultSet rsacc = sttmacc.executeQuery(sqlacc);
            while (rsacc.next()) {
                acctable.addRow(new Object[]{rsacc.getString("ID_Account"), rsacc.getString("Username"), rsacc.getString("Phone_number"), rsacc.getString("Password"), rsacc.getString("Role"), rsacc.getString("log_time")});
                itotalaccount++;
            }

//            ID_acc = (String) tableacc.getValueAt(a, 0);
        } catch (SQLException ex) {
            Logger.getLogger(HomeAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        ListSelectionModel lmacc = tableacc.getSelectionModel();
        lmacc.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        totalacc.setText(Integer.toString(itotalaccount));
    }


    private void dashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardMouseClicked
        // TODO add your handling code here:
        dashboard1.setVisible(true);
        account1.setVisible(false);
        room1.setVisible(false);
        oder1.setVisible(false);

        dashboard.setBackground(new Color(51, 255, 255));
        account.setBackground(new Color(153, 255, 255));
        room.setBackground(new Color(153, 255, 255));
        order.setBackground(new Color(153, 255, 255));
    }//GEN-LAST:event_dashboardMouseClicked

    private void accountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountMouseClicked
        // TODO add your handling code here:
        dashboard1.setVisible(false);
        account1.setVisible(true);
        room1.setVisible(false);
        oder1.setVisible(false);

        dashboard.setBackground(new Color(153, 255, 255));
        account.setBackground(new Color(51, 255, 255));
        room.setBackground(new Color(153, 255, 255));
        order.setBackground(new Color(153, 255, 255));
    }//GEN-LAST:event_accountMouseClicked

    private void roomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roomMouseClicked

        dashboard1.setVisible(false);
        account1.setVisible(false);
        room1.setVisible(true);
        oder1.setVisible(false);

        dashboard.setBackground(new Color(153, 255, 255));
        account.setBackground(new Color(153, 255, 255));
        room.setBackground(new Color(51, 255, 255));
        order.setBackground(new Color(153, 255, 255));


    }//GEN-LAST:event_roomMouseClicked

    private void orderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderMouseClicked

        // TODO add your handling code here:
        dashboard1.setVisible(false);
        account1.setVisible(false);
        room1.setVisible(false);
        oder1.setVisible(true);

        dashboard.setBackground(new Color(153, 255, 255));
        account.setBackground(new Color(153, 255, 255));
        room.setBackground(new Color(153, 255, 255));
        order.setBackground(new Color(51, 255, 255));

    }//GEN-LAST:event_orderMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        // TODO add your handling code here:
        int clogout = JOptionPane.showConfirmDialog(this, "Do you want logout?");
        if (clogout == JOptionPane.YES_NO_OPTION) {
            new Login().Name = "";
            new Login().role = "";
            Login l = new Login();
            l.setLocationRelativeTo(null);
            l.setVisible(true);
            this.dispose();

        }

    }//GEN-LAST:event_logoutMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ID_Order = (String) orderroom.getValueAt(orderroom.getSelectedRow(), 0);
        String sql = "UPDATE oder SET stt_oder = 'Agreed' WHERE ID_oder = ?;";

        String sqlgettroom = "SELECT * FROM `rooms` WHERE `Number_room` = ?";

        String sqlgetorder = "SELECT * FROM `oder` WHERE ID_oder = ?;";

        String sqluproom = "UPDATE `rooms` SET `Stt_room` = 'Non available', `Booking_person_ID` = ? WHERE `rooms`.`Number_room` = ?;";

        if (ID_Order.equals("")) {
            JOptionPane.showMessageDialog(this, "You have not selected!!");
        } else {
            try {
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/" + Config.DATABASENAME, Config.USER, Config.PASS);
                PreparedStatement pstmt = conn.prepareStatement(sql);
                pstmt.setInt(1, Integer.parseInt(ID_Order));

                PreparedStatement psgetorder = conn.prepareStatement(sqlgetorder);
                psgetorder.setInt(1, Integer.parseInt(ID_Order));
                ResultSet rsgetorder = psgetorder.executeQuery();
                rsgetorder.next();

                PreparedStatement psgetbookid = conn.prepareStatement(sqlgettroom);
                psgetbookid.setInt(1, Integer.parseInt(rsgetorder.getString("rooms")));
                ResultSet rsgetbookid = psgetbookid.executeQuery();
                rsgetbookid.next();
//                JOptionPane.showMessageDialog(this, rsgetbookid.getString("Booking_person_ID"));

                if (rsgetbookid.getString("Booking_person_ID").equals("") == false | rsgetbookid.getString("Booking_person_ID").equals("0")) {
                    JOptionPane.showMessageDialog(this, "Phòng đã có người đặt!!");

                } else if (pstmt.executeUpdate() == 1) {
                    PreparedStatement psuproom = conn.prepareStatement(sqluproom);
                    psuproom.setString(1, rsgetorder.getString("ID_User_Oder"));
                    psuproom.setString(2, rsgetorder.getString("rooms"));
                    psuproom.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Successful");

//                    JOptionPane.showMessageDialog(this, "Successful");
                    ID_Order = "";
                    showorder();

                }

            } catch (SQLException ex) {
                Logger.getLogger(HomeAdmin.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ID_Order = (String) orderroom.getValueAt(orderroom.getSelectedRow(), 0);
        String sql = "UPDATE oder SET stt_oder = 'Refuse' WHERE ID_oder = ?;";
        if (ID_Order.equals("")) {
            JOptionPane.showMessageDialog(this, "You have not selected!!");
        } else {
            try {
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/" + Config.DATABASENAME, Config.USER, Config.PASS);
                PreparedStatement pstmt = conn.prepareStatement(sql);
                pstmt.setInt(1, Integer.parseInt(ID_Order));
                if (pstmt.executeUpdate() == 1) {
                    JOptionPane.showMessageDialog(this, "Successful");
                    ID_Order = "";
                    showorder();
//                    this.dispose();
//                    HomeAdmin ha = new HomeAdmin();
//                    ha.setLocationRelativeTo(null);
//                    ha.setVisible(true);
//                    this.dispose();
                }
                conn.close();
//                JOptionPane.showMessageDialog(this, ID_Order);
            } catch (SQLException ex) {
                Logger.getLogger(HomeAdmin.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btaddaccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btaddaccountActionPerformed
        // TODO add your handling code here:
        AddAccount addacc = new AddAccount();
        addacc.setLocationRelativeTo(null);
        addacc.setVisible(true);
        showacc();

//        this.dispose();
    }//GEN-LAST:event_btaddaccountActionPerformed

    private void btdeleteaccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btdeleteaccountActionPerformed
        // TODO add your handling code here:
        int cf = JOptionPane.showConfirmDialog(this, "Do you want delete?");
        if (cf == JOptionPane.YES_OPTION) {
            String sql = "DELETE FROM `account` WHERE `account`.`ID_Account` = ?";
            ID_acc = (String) tableacc.getValueAt(tableacc.getSelectedRow(), 0);
            if (ID_acc.equals("")) {
                JOptionPane.showMessageDialog(this, "You have not selected!!");
            } else {
                try {
                    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/" + Config.DATABASENAME, Config.USER, Config.PASS);
                    PreparedStatement pstmt = conn.prepareStatement(sql);
                    pstmt.setInt(1, Integer.parseInt(ID_acc));
                    if (pstmt.executeUpdate() == 1) {

                        ID_acc = "";
                        JOptionPane.showMessageDialog(this, "Successful");

                        showacc();

                    }

                    conn.close();

                } catch (SQLException ex) {
                    Logger.getLogger(HomeAdmin.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }


    }//GEN-LAST:event_btdeleteaccountActionPerformed

    private void bteditaccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bteditaccountActionPerformed
        // TODO add your handling code here:
        showacc();
    }//GEN-LAST:event_bteditaccountActionPerformed

    private void bteditroomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bteditroomActionPerformed
        // TODO add your handling code here:
        ID_Room = (String) tableroom.getValueAt(tableroom.getSelectedRow(), 0);
        if (ID_Room.equals("")) {
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn để chỉnh sửa!!");
        } else {
            EditRoom editroom = new EditRoom();
            editroom.setLocationRelativeTo(null);
            editroom.setVisible(true);
        }

    }//GEN-LAST:event_bteditroomActionPerformed

    private void bteditaccount1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bteditaccount1ActionPerformed
        // TODO add your handling code here:
        ID_acc = (String) tableacc.getValueAt(tableacc.getSelectedRow(), 0);
        if (ID_acc.equals("")) {
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn để chỉnh sửa!!");
        } else {
            EditAccount editacc = new EditAccount();
            editacc.setLocationRelativeTo(null);
            editacc.setVisible(true);
        }


    }//GEN-LAST:event_bteditaccount1ActionPerformed

    private void bteditaccount2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bteditaccount2ActionPerformed
        // TODO add your handling code here:
        showorder();
    }//GEN-LAST:event_bteditaccount2ActionPerformed

    private void btaddroomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btaddroomActionPerformed
        // TODO add your handling code here:
        AddRoom ar = new AddRoom();
        ar.setLocationRelativeTo(null);
        ar.setVisible(true);

    }//GEN-LAST:event_btaddroomActionPerformed

    private void bteditaccount3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bteditaccount3ActionPerformed
        // TODO add your handling code here:
        showroom();
    }//GEN-LAST:event_bteditaccount3ActionPerformed

    private void btdeleteroomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btdeleteroomActionPerformed
        // TODO add your handling code here:
        int cf = JOptionPane.showConfirmDialog(this, "Do you want delete?");
        if (cf == JOptionPane.YES_OPTION) {
            String sql = "DELETE FROM `rooms` WHERE `rooms`.`ID_Room` = ?";
            ID_Room = (String) tableroom.getValueAt(tableroom.getSelectedRow(), 0);
            if (ID_Room.equals("")) {
                JOptionPane.showMessageDialog(this, "You have not selected!!");
            } else {
                try {
                    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/" + Config.DATABASENAME, Config.USER, Config.PASS);
                    PreparedStatement pstmt = conn.prepareStatement(sql);
                    pstmt.setInt(1, Integer.parseInt(ID_Room));
                    if (pstmt.executeUpdate() == 1) {

                        ID_Room = "";

                        JOptionPane.showMessageDialog(this, "Successful");
                        showroom();

                    }

                    conn.close();

                } catch (SQLException ex) {
                    Logger.getLogger(HomeAdmin.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }


    }//GEN-LAST:event_btdeleteroomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel account;
    private javax.swing.JPanel account1;
    private javax.swing.JButton btaddaccount;
    private javax.swing.JButton btaddroom;
    private javax.swing.JButton btdeleteaccount;
    private javax.swing.JButton btdeleteroom;
    private javax.swing.JButton bteditaccount;
    private javax.swing.JButton bteditaccount1;
    private javax.swing.JButton bteditaccount2;
    private javax.swing.JButton bteditaccount3;
    private javax.swing.JButton bteditroom;
    private javax.swing.JPanel dashboard;
    private javax.swing.JPanel dashboard1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel logout;
    private javax.swing.JPanel oder1;
    private javax.swing.JPanel order;
    private javax.swing.JTable orderroom;
    private javax.swing.JPanel room;
    private javax.swing.JPanel room1;
    private javax.swing.JTable tableacc;
    private javax.swing.JTable tableroom;
    private javax.swing.JLabel totalacc;
    private javax.swing.JLabel totalorder;
    private javax.swing.JLabel totalrooms;
    // End of variables declaration//GEN-END:variables
}
